<html>
    <head>
        <title>Some amazing website</title>

        <?php $this->assets->outputCss(); ?>
    </head>

    <body>
        <div class="container">

        <?= $this->tag->form("phalcon-test/signup/register"); ?>

            <div class="form-group">
                <label for="name">Name</label>
                <input id="name" class="form-control" type="text" />
            </div>

            <div class="form-group">
                <label for="password">Password</label>
                <input id="password" class="form-control" type="password" />
            </div>

            <div class="form-group">
                <label for="password-confirm">Confirm Password</label>
                <input id="password-confirm" class="form-control" type="password" />
            </div>
        
            <div class="form-group">
                <label for="email">Email</label>
                <input id="email" class="form-control" type="text" />
            </div>
        
            <input type="submit" class="btn btn-primary" value="Register" />
        </form>

        
        </div>

        <?php $this->assets->outputJs(); ?>
    </body>
<html>