<html>
    <head>
        <title>Some amazing website</title>

        <?php $this->assets->outputCss(); ?>
    </head>

    <body>
        <div class="container">

        <h1>
            <?= 
                $this->tag->linkTo(
                    'phalcon-test/signup',
                    'Sign Up Here!'
                );
            ?>
        </h1>
        </div>

        <?php $this->assets->outputJs(); ?>
    </body>
<html>