<div class="container">
    <p><?= $this->flashSession->output() ?></p>

    <?= $this->tag->form("phalcon-test/login/submit"); ?>
        
        <div class="form-group">
            <label for="email">Email</label>
            <?php echo $form->render('email'); ?>
        </div>

        <div class="form-group">
            <label for="password">Password</label>
            <?php echo $form->render('password'); ?>
        </div>

        <div class="form-group">
            <?php echo $form->render('submit'); ?>
        </div>
        
        <input type='hidden' name='<?= $this->security->getTokenKey() ?>' value='<?= $this->security->getToken() ?>'/>

    <?= $this->tag->endForm() ?>

    <p>Login to your Application account below.
        <?= $this->tag->linkTo('phalcon-test/signup', 'Need to register?') ?>
    </p>
</div>
