<div class="container">
    <p><?php echo $this->flashSession->output() ?></p>
    <?= $this->tag->form(['phalcon-test/account/editSubmit', 'autocomplete' => 'off']); ?>

        <div class="form-group">
            <label for="first_name">First Name</label>
            <?= $form->render('first_name'); ?>
        </div>

        <div class="form-group">
            <label for="last_name">Last Name</label>
            <?= $form->render('last_name'); ?>
        </div>

        <div class="form-group">
            <label for="email">Email</label>
            <?= $form->render('email'); ?>
        </div>

        <div class="form-group">
            <label for="edit_password">Password</label>
            <?= $form->render('edit_password'); ?>
        </div>

        <div class="form-group">
            <label for="edit_password_confirm">Confirm Password</label>
            <?= $form->render('edit_password_confirm'); ?>
        </div>

        <div class="form-group">
            <?= $form->render('submit'); ?>
        </div>
        
    <?= $this->tag->endForm() ?>

</div>