<!DOCTYPE html>
<html>
    <head>
        <title>Eaty</title>
        <?php 
            echo $this->tag->getTitle();
            echo $this->tag->stylesheetLink('https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css');
        ?>
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Eaty</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/phalcon-test/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/phalcon-test/login">Login</a>
                    </li>
                    <li class="nav-item ml-auto">
                        <a class="nav-link" href="/phalcon-test/signup">Sign Up</a>
                    </li>
                </ul>
            </div>
        </nav>

        <!-- Main Content -->
        <?php echo $this->getContent(); ?>
        
        <?php
            echo $this->tag->javascriptInclude('https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.bundle.min.js');
        ?>

        <?php $this->assets->outputJs(); ?>
    </body>
<html>